### ISSUE TITLE
Panic runtime error 

### ISSUE THREAD

**Issue by MR-pentestGuy** [Shivangx01b/CorsMe#3]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x675de5]

goroutine 36 [running]:
main.requester(0xc000188390, 0x6f19e2, 0x3, 0xc0001a0100, 0x19, 0xc000050ed0, 0x2, 0x2, 0x6f1830, 0x1)
        /home/sanath/go/src/github.com/shivangx01b/CorsMe/corsme.go:103 +0xe5
main.totalwaystotest(0xc000188390, 0x6f19e2, 0x3, 0xc0001a0100, 0x19, 0x0, 0x6f1830, 0x1)
        /home/sanath/go/src/github.com/shivangx01b/CorsMe/corsme.go:219 +0x18a
main.main.func1(0xc000180320, 0xc00018c000, 0xc000188390)
        /home/sanath/go/src/github.com/shivangx01b/CorsMe/corsme.go:290 +0xbb
created by main.main
        /home/sanath/go/src/github.com/shivangx01b/CorsMe/corsme.go:287 +0x48c

**Comment by Shivangx01b** [comment]
Hi there,
I appreciate your concern but it's more likely your golang installation issue ... run in other place like vps/local with fresh golang installation ..and if issue still exists send a screen shot  and raise the issue again
